apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deploy
  labels:
    name: hello-world-app-deploy
    app: demo-hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-world-app-pod
      app: demo-hello-world-app
  template:
    metadata:
      name: hello-world-app-pod
      labels:
        name: hello-world-app-pod
        app: demo-hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: gmdjaveed/jg-hello-world-java-docker:2.0
          ports:
            - containerPort: 80